services:
  backend:
    build: ./backend
    container_name: akuma_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./results:/app/results
    environment:
      - PYTHONPATH=/app
    networks:
      - akuma_network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: akuma_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - akuma_network
    restart: unless-stopped

networks:
  akuma_network:
    driver: bridge
