version: '3.8'

services:
  backend:
    build: ./backend
    container_name: akuma_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///data/scans.db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - akuma_network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: akuma_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - akuma_network
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: akuma_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - akuma_network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  akuma_network:
    driver: bridge
